{{- if and .Values.mariadb.enabled (not .Values.mariadb.auth.existingSecretName) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "librebooking.fullname" . }}-mariadb
  labels:
    {{- include "librebooking.labels" . | nindent 4 }}
type: Opaque
stringData:
  mysql-root-password: "{{ .Values.mariadb.auth.rootPassword }}"
  mysql-password: "{{ .Values.mariadb.auth.password }}"
{{- end }}
