{{- if and .Values.persistence.logs.enabled (not .Values.persistence.logs.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "librebooking.fullname" . }}-logs
  labels:
    {{- include "librebooking.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.persistence.logs.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.persistence.logs.size }}
  {{- if .Values.persistence.logs.storageClass }}
  storageClassName: {{ .Values.persistence.logs.storageClass }}
  {{- end }}
{{- end }}
