{{- if and .Values.externalDatabase.enabled (not .Values.externalDatabase.existingSecretName) .Values.externalDatabase.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "librebooking.fullname" . }}-db
  labels:
    {{- include "librebooking.labels" . | nindent 4 }}
type: Opaque
stringData:
  db-password: "{{ .Values.externalDatabase.password }}"
{{- end }}
