{{- if and (not .Values.app.existingSecretName) .Values.app.installPassword }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "librebooking.fullname" . }}-install
  labels:
    {{- include "librebooking.labels" . | nindent 4 }}
type: Opaque
stringData:
  LB_INSTALL_PASSWORD: "{{ .Values.app.installPassword }}"
{{- end }}
